theme: jekyll-theme-minimal
title: Benjamin Marek
description: Stanford 2028 | Economics and Classics

social_links:
  - name: Email
    url: mailto:bmarek@stanford.edu
  - name: LinkedIn
    url: https://linkedin.com/in/b-marek
