theme: jekyll-theme-minimal
title: Benjamin Marek
description: >
  <strong><span style="font-size: 1.2em;">Stanford 2028 | Econ + Classics</span></strong><br><br>
  This site collects short analytical essays on economics, policy, and international affairs. <br>
  <br>
  <a href="/review/" style="font-size: 1.2em; display:block; margin-bottom:0.3em;">Stanford Review</a>
  <a href="/resume/" style="font-size: 1.2em; display:block; margin-bottom:0.3em;">Resume</a>
  <a href="/about/" style="font-size: 1.2em; display:block; margin-bottom:0.3em;">About</a><br>
  <br>
  <a href="mailto:bmarek@stanford.edu">Email</a> Â·
  <a href="https://linkedin.com/in/b-marek">LinkedIn</a>

show_downloads: false
google_analytics:
github: false
