theme: jekyll-theme-minimal
title: Benjamin Marek
description: >
  Stanford 2028 | Economics and Classics <br>
  <br>
  <a href="/review/">Stanford Review Articles</a><br>
  <a href="/resume/">Resume</a><br>
  <a href="/about/">About</a><br>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <a href="mailto:bmarek@stanford.edu">Email</a> ·
  <a href="https://linkedin.com/in/b-marek">LinkedIn</a> ·
  <a href="https://stanfordreview.org/author/ben-marek/">Stanford Review Profile</a>

show_downloads: false
google_analytics:
github: false
