theme: jekyll-theme-minimal
title: Benjamin Marek
description: Stanford 2028 | Economics and Classics

nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Stanford Review
    url: /stanford-review/
