theme: jekyll-theme-minimal
title: Benjamin Marek
description: >
  Stanford 2028 | Economics and Classics <br>
  <a href="mailto:bmarek@stanford.edu">Email</a> Â·
  <a href="https://linkedin.com/in/b-marek">LinkedIn</a>
